on: 
  push:
    branches:
      - feature

jobs:
  build_1:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: list files
        run: |
          ls -la

      - name: Display Python version
        run: |
          python hello.py
  
  build_2:

    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: list files
        run: |
          ls -la

      - name: Display Python version
        run: |
          python hello2.py